# Generated by Django 2.0.4 on 2018-04-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
            ],
            options={
                'indexes': [],
                'verbose_name': 'cliente',
                'proxy': True,
                'verbose_name_plural': 'clientes',
            },
            bases=('crm.person',),
        ),
        migrations.AddField(
            model_name='person',
            name='person_type',
            field=models.CharField(choices=[('c', 'cliente'), ('f', 'fornecedor')], default='c', max_length=1, verbose_name='cliente ou fornecedor'),
        ),
    ]
